spring.application.name=front-ms
server.port=8080

livro.ms.url=${LIVRO_MS_URL:http://localhost:8081}
autor.ms.url=${AUTOR_MS_URL:http://localhost:8082}

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
